name: Build debian:trixie

on:
  push:
    branches: [ "main" ]
    paths:
      - 'trixie/**'
      - '.github/workflows/debian-trixie.yaml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: debian            # 仓库名统一为 debian

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Normalize repository owner
        shell: bash
        run: echo "IMAGE_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=trixie               # 语义标签
            type=sha,prefix=trixie-             # SHA 标签，例如 trixie-abc1234

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./trixie
          file: ./trixie/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}